server:
  port: 8742
  servlet:
    context-path: /auth-service
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/mydb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.security: TRACE
